# Generated by Django 5.1.2 on 2024-10-16 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='value',
        ),
    ]
