# Generated by Django 5.1.2 on 2024-10-16 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_remove_car_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
